name: Update README Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Optional: run standard-version to bump version & update CHANGELOG.md
      # Uncomment this step if you're using standard-version in your release flow.
      - name: Generate changelog with standard-version (optional)
        if: ${{ always() }}
        run: |
          # run standard-version only if there are conventional commits since last tag
          npx standard-version --no-verify || echo "standard-version exited with non-zero (maybe no new release)"

      - name: Generate README changelog from commits
        run: node ./scripts/generate-changelog-from-commits.js

      - name: Commit & push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md CHANGELOG.md package.json package-lock.json || true
          # Exit early if nothing changed
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "chore: update README changelog from commits [skip ci]" || echo "Nothing to commit"
          git push origin HEAD:main
